import PDFDocument from 'pdfkit';

export function workOrderPdf(order, items) {
  const doc = new PDFDocument({ size: 'LETTER', margin: 36 });

  // Header
  doc.fontSize(18).text('Work Order', { align: 'right' });
  doc.moveDown(0.5);

  // Summary block
  const label = (k, v) => doc.fontSize(10).text(`${k}: `, { continued: true }).font('Helvetica-Bold').text(v || '—').font('Helvetica');

  label('WO #', order.work_order_number);
  label('Job #', order.job_number);
  label('Job Name', order.job_name);
  label('PM', order.job_pm);
  label('Superintendent', order.job_superintendent);
  label('Address', order.job_address);
  label('Date Issued', order.date_issued);
  label('Material Delivery', order.material_delivery_date || '—');
  label('Requested Completion', (order.requested_completion_dates || []).join(', ') || '—');
  label('Completion', order.completion_varies ? 'Varies' : order.completion_date || '—');
  label('Status', order.status);

  doc.moveDown(0.75);
  doc.fontSize(12).text('Items', { underline: true });

  items.forEach((it, idx) => {
    doc.moveDown(0.35);
    doc.font('Helvetica-Bold').text(`${idx + 1}. ${it.type}  •  Elevation: ${it.elevation || '—'}  •  Qty: ${it.quantity}`);
    const dates = (it.completion_dates || []).map((d) => d.completion_date).join(', ');
    doc.font('Helvetica').fontSize(10).text(`Completion Dates: ${dates || '—'}`);
  });

  doc.moveDown(1);
  doc.fontSize(9).fillColor('#666').text('Generated by Work Order API', { align: 'right' });

  doc.end();
  return doc;
}
